// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package db

import (
	"context"
	"database/sql"
)

const createCommand = `-- name: CreateCommand :one
INSERT INTO commands (
    id,
    session_id,
    timestamp,
    command,
    cwd,
    repo,
    branch,
    exit_code,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, session_id, timestamp, command, cwd, repo, branch, exit_code, created_at
`

type CreateCommandParams struct {
	ID        string
	SessionID string
	Timestamp int64
	Command   string
	Cwd       sql.NullString
	Repo      sql.NullString
	Branch    sql.NullString
	ExitCode  sql.NullInt64
	CreatedAt int64
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error) {
	row := q.db.QueryRowContext(ctx, createCommand,
		arg.ID,
		arg.SessionID,
		arg.Timestamp,
		arg.Command,
		arg.Cwd,
		arg.Repo,
		arg.Branch,
		arg.ExitCode,
		arg.CreatedAt,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.Command,
		&i.Cwd,
		&i.Repo,
		&i.Branch,
		&i.ExitCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommand = `-- name: DeleteCommand :exec
DELETE FROM commands
WHERE id = ?
`

func (q *Queries) DeleteCommand(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCommand, id)
	return err
}

const getCommand = `-- name: GetCommand :one
SELECT id, session_id, timestamp, command, cwd, repo, branch, exit_code, created_at
FROM commands
WHERE id = ?
`

func (q *Queries) GetCommand(ctx context.Context, id string) (Command, error) {
	row := q.db.QueryRowContext(ctx, getCommand, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.Command,
		&i.Cwd,
		&i.Repo,
		&i.Branch,
		&i.ExitCode,
		&i.CreatedAt,
	)
	return i, err
}

const listCommandsByRepo = `-- name: ListCommandsByRepo :many
SELECT id, session_id, timestamp, command, cwd, repo, branch, exit_code, created_at
FROM commands
WHERE repo = ?
ORDER BY timestamp DESC, created_at DESC
LIMIT ? OFFSET ?
`

type ListCommandsByRepoParams struct {
	Repo   sql.NullString
	Limit  int64
	Offset int64
}

func (q *Queries) ListCommandsByRepo(ctx context.Context, arg ListCommandsByRepoParams) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, listCommandsByRepo, arg.Repo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Command,
			&i.Cwd,
			&i.Repo,
			&i.Branch,
			&i.ExitCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommandsBySession = `-- name: ListCommandsBySession :many
SELECT id, session_id, timestamp, command, cwd, repo, branch, exit_code, created_at
FROM commands
WHERE session_id = ?
ORDER BY timestamp DESC, created_at DESC
LIMIT ? OFFSET ?
`

type ListCommandsBySessionParams struct {
	SessionID string
	Limit     int64
	Offset    int64
}

func (q *Queries) ListCommandsBySession(ctx context.Context, arg ListCommandsBySessionParams) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, listCommandsBySession, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Command,
			&i.Cwd,
			&i.Repo,
			&i.Branch,
			&i.ExitCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommandsInTimeRange = `-- name: ListCommandsInTimeRange :many
SELECT id, session_id, timestamp, command, cwd, repo, branch, exit_code, created_at
FROM commands
WHERE timestamp >= ?
  AND timestamp <= ?
ORDER BY timestamp DESC, created_at DESC
LIMIT ? OFFSET ?
`

type ListCommandsInTimeRangeParams struct {
	Timestamp   int64
	Timestamp_2 int64
	Limit       int64
	Offset      int64
}

func (q *Queries) ListCommandsInTimeRange(ctx context.Context, arg ListCommandsInTimeRangeParams) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, listCommandsInTimeRange,
		arg.Timestamp,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Command,
			&i.Cwd,
			&i.Repo,
			&i.Branch,
			&i.ExitCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCommands = `-- name: ListRecentCommands :many
SELECT id, session_id, timestamp, command, cwd, repo, branch, exit_code, created_at
FROM commands
ORDER BY timestamp DESC, created_at DESC
LIMIT ? OFFSET ?
`

type ListRecentCommandsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListRecentCommands(ctx context.Context, arg ListRecentCommandsParams) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, listRecentCommands, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Command,
			&i.Cwd,
			&i.Repo,
			&i.Branch,
			&i.ExitCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
