// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package db

import (
	"context"
	"database/sql"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (
    id,
    session_id,
    title,
    summary,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, session_id, title, summary, created_at
`

type CreateMemoryParams struct {
	ID        string
	SessionID string
	Title     sql.NullString
	Summary   string
	CreatedAt int64
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, createMemory,
		arg.ID,
		arg.SessionID,
		arg.Title,
		arg.Summary,
		arg.CreatedAt,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories
WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMemory, id)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, session_id, title, summary, created_at
FROM memories
WHERE id = ?
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const getMemoryBySession = `-- name: GetMemoryBySession :one
SELECT id, session_id, title, summary, created_at
FROM memories
WHERE session_id = ?
`

func (q *Queries) GetMemoryBySession(ctx context.Context, sessionID string) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemoryBySession, sessionID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listMemories = `-- name: ListMemories :many
SELECT id, session_id, title, summary, created_at
FROM memories
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListMemoriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListMemories(ctx context.Context, arg ListMemoriesParams) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Title,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemories = `-- name: SearchMemories :many
SELECT memories.id, memories.session_id, memories.title, memories.summary, memories.created_at, bm25(memories_fts) AS score
FROM memories
JOIN memories_fts ON memories.rowid = memories_fts.rowid
WHERE memories_fts.title MATCH ?2
UNION
SELECT memories.id, memories.session_id, memories.title, memories.summary, memories.created_at, bm25(memories_fts) AS score
FROM memories
JOIN memories_fts ON memories.rowid = memories_fts.rowid
WHERE memories_fts.summary MATCH ?2
UNION
SELECT memories.id, memories.session_id, memories.title, memories.summary, memories.created_at, bm25(memories_fts) AS score
FROM memories
JOIN memories_fts ON memories.rowid = memories_fts.rowid
WHERE memories_fts.commands MATCH ?2
ORDER BY score
LIMIT ?1
`

type SearchMemoriesParams struct {
	LimitVal int64
	Query    string
}

type SearchMemoriesRow struct {
	ID        string
	SessionID string
	Title     sql.NullString
	Summary   string
	CreatedAt int64
	Score     float64
}

func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]SearchMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMemories, arg.LimitVal, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoriesRow
	for rows.Next() {
		var i SearchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Title,
			&i.Summary,
			&i.CreatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories
SET
    title = ?,
    summary = ?
WHERE id = ?
RETURNING id, session_id, title, summary, created_at
`

type UpdateMemoryParams struct {
	Title   sql.NullString
	Summary string
	ID      string
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, updateMemory, arg.Title, arg.Summary, arg.ID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}
