// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package db

import (
	"context"
)

const getMetadata = `-- name: GetMetadata :one
SELECT "key", value FROM metadata WHERE key = ?
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (Metadata, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var i Metadata
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const upsertMetadata = `-- name: UpsertMetadata :one
INSERT INTO metadata (
    key,
    value
)
VALUES (
    ?,
    ?
)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
RETURNING "key", value
`

type UpsertMetadataParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) (Metadata, error) {
	row := q.db.QueryRowContext(ctx, upsertMetadata, arg.Key, arg.Value)
	var i Metadata
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}
