// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Command struct {
	ID        string
	SessionID string
	Timestamp int64
	Command   string
	Cwd       sql.NullString
	Repo      sql.NullString
	Branch    sql.NullString
	ExitCode  sql.NullInt64
	CreatedAt int64
}

type Memory struct {
	ID        string
	SessionID string
	Title     sql.NullString
	Summary   string
	CreatedAt int64
}

type Session struct {
	ID           string
	Repo         string
	Branch       sql.NullString
	StartTs      int64
	EndTs        int64
	CommandCount int64
	CreatedAt    int64
	UpdatedAt    int64
}
