// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    repo,
    branch,
    start_ts,
    end_ts,
    command_count,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, repo, branch, start_ts, end_ts, command_count, created_at, updated_at
`

type CreateSessionParams struct {
	ID           string
	Repo         string
	Branch       sql.NullString
	StartTs      int64
	EndTs        int64
	CommandCount int64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Repo,
		arg.Branch,
		arg.StartTs,
		arg.EndTs,
		arg.CommandCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.Branch,
		&i.StartTs,
		&i.EndTs,
		&i.CommandCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, repo, branch, start_ts, end_ts, command_count, created_at, updated_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.Branch,
		&i.StartTs,
		&i.EndTs,
		&i.CommandCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentSessions = `-- name: ListRecentSessions :many
SELECT id, repo, branch, start_ts, end_ts, command_count, created_at, updated_at
FROM sessions
ORDER BY end_ts DESC, updated_at DESC
LIMIT ? OFFSET ?
`

type ListRecentSessionsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListRecentSessions(ctx context.Context, arg ListRecentSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.Branch,
			&i.StartTs,
			&i.EndTs,
			&i.CommandCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByRepo = `-- name: ListSessionsByRepo :many
SELECT id, repo, branch, start_ts, end_ts, command_count, created_at, updated_at
FROM sessions
WHERE repo = ?
ORDER BY end_ts DESC, updated_at DESC
LIMIT ? OFFSET ?
`

type ListSessionsByRepoParams struct {
	Repo   string
	Limit  int64
	Offset int64
}

func (q *Queries) ListSessionsByRepo(ctx context.Context, arg ListSessionsByRepoParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByRepo, arg.Repo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.Branch,
			&i.StartTs,
			&i.EndTs,
			&i.CommandCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSessionForCommand = `-- name: TouchSessionForCommand :one
UPDATE sessions
SET
    end_ts = ?,
    command_count = command_count + 1,
    updated_at = ?
WHERE id = ?
RETURNING id, repo, branch, start_ts, end_ts, command_count, created_at, updated_at
`

type TouchSessionForCommandParams struct {
	EndTs     int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) TouchSessionForCommand(ctx context.Context, arg TouchSessionForCommandParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, touchSessionForCommand, arg.EndTs, arg.UpdatedAt, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.Branch,
		&i.StartTs,
		&i.EndTs,
		&i.CommandCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    repo = ?,
    branch = ?,
    start_ts = ?,
    end_ts = ?,
    command_count = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, repo, branch, start_ts, end_ts, command_count, created_at, updated_at
`

type UpdateSessionParams struct {
	Repo         string
	Branch       sql.NullString
	StartTs      int64
	EndTs        int64
	CommandCount int64
	UpdatedAt    int64
	ID           string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.Repo,
		arg.Branch,
		arg.StartTs,
		arg.EndTs,
		arg.CommandCount,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.Branch,
		&i.StartTs,
		&i.EndTs,
		&i.CommandCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
